### ISSUE TITLE
showtext and treemap

### ISSUE THREAD

**Issue by feng-1985** [yixuan/showtext#8]
Hi!
    I got a problem with chinese character in treemap function. Here is the code:
library(treemap)
data(GNI2014)
levels(GNI2014$continent) <- c("非洲","南极洲","亚洲","欧洲","北美洲","大洋洲","公海","南美洲")
library(showtext)
showtext.auto(enable = TRUE)
font.add('SimSun', 'simsun.ttc')
pdf(file="testtree.pdf", width = 8,height = 8)

treemap(GNI2014,
        index=c("continent", "iso3"),
        vSize="population",
        vColor="GNI",
        type="value")

dev.off()

Here is the question:  The testtree.pdf can't show the chinese character!

**Comment by yixuan** [comment]
This is because you didn't tell `treemap()` to use the font.

``` r
library(showtext)
showtext.auto(enable = TRUE)
font.add('SimSun', 'simsun.ttc')

pdf(file = "testtree.pdf", width = 8,height = 8)
treemap(GNI2014, index = c("continent", "iso3"), vSize = "population",
        vColor = "GNI", type = "value", fontfamily.labels = "SimSun")
dev.off()
```

![testtree_01](https://cloud.githubusercontent.com/assets/216398/17212611/48dd1850-549e-11e6-9046-91759804182c.png)

But as you see, the `SimSun` font does not produce nice English characters, so I would suggest using the `wqy-microhei` font instead.

``` r
library(showtext)
showtext.auto(enable = TRUE)
pdf(file = "testtree.pdf", width = 8,height = 8)
treemap(GNI2014, index = c("continent", "iso3"), vSize = "population",
        vColor = "GNI", type = "value", fontfamily.labels = "wqy-microhei")
dev.off()
```

![testtree_02](https://cloud.githubusercontent.com/assets/216398/17212617/4db95988-549e-11e6-8080-3ed4cc83bdad.png)

**Comment by feng-1985** [comment]
Oh yes! thank you very much!
